import os
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail
from database import get_top_movers, get_latest_scores


def send_daily_digest():
    """Send daily digest email with top risk movers."""
    api_key = os.environ.get("SENDGRID_API_KEY")
    from_email = os.environ.get("DIGEST_FROM_EMAIL", "georisk@example.com")
    to_email = os.environ.get("DIGEST_TO_EMAIL")

    if not api_key or not to_email:
        print("SendGrid not configured — skipping email. Set SENDGRID_API_KEY and DIGEST_TO_EMAIL.")
        return False

    movers = get_top_movers(3)
    latest = get_latest_scores()

    if not movers:
        print("No data to send in digest.")
        return False

    # Build email body
    lines = ["<h2>GeoRisk Pulse - Daily Digest</h2>", "<h3>Top Risk Movers</h3>", "<table border='1' cellpadding='8'>"]
    lines.append("<tr><th>Region</th><th>Score</th><th>Change</th></tr>")
    for m in movers:
        change = m["change"]
        arrow = "&#9650;" if change > 0 else "&#9660;" if change < 0 else "&#9654;"
        color = "red" if change > 0 else "green" if change < 0 else "gray"
        lines.append(
            f"<tr><td>{m['region']}</td><td>{m['current_score']:.1f}</td>"
            f"<td style='color:{color}'>{arrow} {change:+.1f}</td></tr>"
        )
    lines.append("</table>")

    lines.append("<h3>All Regions</h3><ul>")
    for s in latest:
        lines.append(f"<li><b>{s['region']}</b>: {s['score']:.1f} ({s['headline_count']} headlines)</li>")
    lines.append("</ul>")
    lines.append("<p><i>Generated by GeoRisk Pulse</i></p>")

    html_body = "\n".join(lines)

    message = Mail(
        from_email=from_email,
        to_emails=to_email,
        subject="GeoRisk Pulse - Daily Risk Digest",
        html_content=html_body,
    )

    try:
        sg = SendGridAPIClient(api_key)
        sg.send(message)
        print(f"Digest email sent to {to_email}")
        return True
    except Exception as e:
        print(f"Failed to send digest: {e}")
        return False
